embeddings {
  tensor_name: "Year:00512"
  metadata_path: "00512/Year/metadata.tsv"
  tensor_path: "00512/Year/tensors.tsv"
}
embeddings {
  tensor_name: "Month:00512"
  metadata_path: "00512/Month/metadata.tsv"
  tensor_path: "00512/Month/tensors.tsv"
}
embeddings {
  tensor_name: "Weekday Name:00512"
  metadata_path: "00512/Weekday Name/metadata.tsv"
  tensor_path: "00512/Weekday Name/tensors.tsv"
}
embeddings {
  tensor_name: "Day:00512"
  metadata_path: "00512/Day/metadata.tsv"
  tensor_path: "00512/Day/tensors.tsv"
}
